# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-02 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0006_auto_20171030_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradebucket',
            name='quantity',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tradestock',
            name='quantity',
            field=models.FloatField(),
        ),
    ]
