# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 18:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_auto_20171109_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='has_bank_linked',
        ),
    ]
